# encoding: utf-8
name: emotiburn
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.17.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/ 